### ISSUE TITLE
I am concerned about the scope of this project

### ISSUE THREAD

**Issue by pjohnmeyer** [arielsarah/liftoff-assignments#1]
First of all, it is obvious this is something you have really put a lot of thought into. Your feature list is very well thought out.

I do think we will need to trim the feature list, though. Can we solve the farm's core problem by, for example, just implementing the Barn Manager / admin side of things for now? The feeding schedules would still be paper, but they would be printed from the computerized system?

**Comment by arielsarah** [comment]
I definitely want to edit the MVP. Not all the features will be in the first release. I like the idea of generating a printed list. Is that easier than displaying on screen?

**Comment by pjohnmeyer** [comment]
I wasn't suggesting you skip displaying it on-screen -- although you could. By sticking to a printable feed sheet, though, you might be able to, for example, implement having logins for feeders "later." That would just be one example of how we can reduce scope, and iterate on changes to the existing processes at the farm. There may be other ways and we can identify that in story mapping.

**Comment by pjohnmeyer** [comment]
We discussed this in class and I'm satisfied with where you're going; once the project outline is updated feel free to close this issue.

**Comment by arielsarah** [comment]
added details regarding user login being part of a second release
