### ISSUE TITLE
Link to project tracker is missing

### ISSUE THREAD

**Issue by pjohnmeyer** [arielsarah/liftoff-assignments#2]
[The assignment](https://education.launchcode.org/liftoff/assignments/project-outline/) says:

> Project Tracker: We talked about various project tracking tools Pivotal, Trello, and GitHub Projects. Whichever you commit to using link here.

The intent was you should link to your project tracker from your Project Outline.

**Comment by arielsarah** [comment]
Added, thank you!
https://github.com/arielsarah/liftoff-assignments/projects/1
