### ISSUE TITLE
Technology selection

### ISSUE THREAD

**Issue by pjohnmeyer** [arielsarah/liftoff-assignments#3]
Am I understanding correctly that you need to learn all four technologies listed on your project outline?

Do you think that is well-advised?

**Comment by arielsarah** [comment]
I have used Bootstrap before but I want to explore more of it. 

Are there other frameworks that would help me with this type of project that I don't have to learn? Would Thymeleaf be useful?

**Comment by pjohnmeyer** [comment]
Okay, so you're already familiar with Bootstrap.

My concern is more about learning a new language (C#) **and** the associated framework (ASP.net MVC core) **and** OAuth. That's a lot to learn. If you already know Java with Thymeleaf you may want to stick with that, and focus on learning OAuth or some other thing to support your features.

**Comment by pjohnmeyer** [comment]
Similarly to #1 we discussed this in class and I'm satisfied with where you're going. Closing this one.
