### ISSUE TITLE
P3: How do I know which stories and wireframes are part of your MVP?

### ISSUE THREAD

**Issue by pjohnmeyer** [arielsarah/liftoff-assignments#5]
You have a good quantity of stories and wireframes, this is great!

It's not clear to me, though, that you've yet identified your MVP. Maybe you have and I'm just not seeing it?

Part of this could have to do with how you've organized your stories; since your columns in project tracker are features, there are no columns for "backlog" or "mvp" or anything like that. At first glance I really liked how you had organized this, but it seems like there's nowhere for a story to "go" as it progresses? Does that make sense?

A typical project board would have columns reflective of the _state_ of the ticket, e.g.:

Backlog --> Current Sprint --> In Progress --> Done

and the story would move across that board as things get done.

Or, maybe you could just add an emoji like :boom: or something to the ones that are MVP?

Think about it and let me know what you figure out.

**Comment by arielsarah** [comment]
I tried another format before I tried this one. My husband suggested it. I think I was a bit confused about how to organize user stories into epics and then into progress columns. Is there a good example that I can look at?

**Comment by pjohnmeyer** [comment]
The GitHub project docs is a good starting point; they show the "automated Kanban" template in their docs:

https://help.github.com/articles/about-project-boards/

But, that is the bare minimum. I'll ask on Slack for some other resources.

Really, you can do it however you want. As long as I can look at your project and identify:

1. Which stories are MVP and which ones are not
2. Which ones are in progress and which ones are not
3. Which epics/features/wireframes they relate to

3 is a little fuzzy because sometimes the connection is intuited, not explicit, but explicit is always good.

**Comment by pjohnmeyer** [comment]
Just wanted to add, I actually kind of like the grid you came up with, but it feels more like a story map than a project tracker; it's a shame that you can't just enter the data once but see them displayed in both ways.

**Comment by pjohnmeyer** [comment]
Here are some examples from mentors:

https://github.com/ryuhhnn/liftoff-db/projects
https://github.com/lindskelsey/liftoff-cards-planning/projects

Both of them seem to have made projects for their MVPs. The second one seems like a better example in that the user stories in the "Ready to be Worked" column are properly worded and spelled out. But, having two examples might still be helpful.
